import base from './index.js';

const enhancement = String.raw`
<style id="pm-interactive-style">
.pm-dash{margin-top:14px}.pm-dash-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pm-chart{min-height:300px}.pm-legend{display:flex;flex-wrap:wrap;gap:12px;margin-top:10px}.pm-leg{display:flex;align-items:center;gap:6px;font-size:11px;color:#9db0c4}.pm-dot{width:10px;height:10px;border-radius:3px;display:inline-block}.pm-click{cursor:pointer;transition:.15s transform,.15s border-color}.pm-click:hover{transform:translateY(-2px);border-color:#5791ff!important}.pm-detail{position:fixed;inset:0;background:rgba(0,0,0,.62);display:none;align-items:center;justify-content:center;padding:20px;z-index:2000}.pm-detail.open{display:flex}.pm-detail-box{width:min(980px,96vw);max-height:86vh;overflow:auto;background:#0d1a2b;border:1px solid #355678;border-radius:18px;padding:18px;box-shadow:0 30px 90px rgba(0,0,0,.55)}.pm-detail-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.pm-detail table{font-size:12px}.pm-empty{padding:25px;text-align:center;color:#91a4ba}.pm-bar-row{display:grid;grid-template-columns:140px 1fr 42px;gap:8px;align-items:center;margin:9px 0}.pm-bar{height:16px;background:#12243a;border-radius:8px;overflow:hidden}.pm-bar>i{display:block;height:100%;border-radius:8px}.pm-kpi-note{font-size:10px;color:#7f93a8;margin-top:4px}@media(max-width:900px){.pm-dash-grid{grid-template-columns:1fr}.pm-bar-row{grid-template-columns:105px 1fr 36px}}
</style>`;

function injection(){return String.raw`
<div class="pm-dash" id="pmDash">
  <div class="pm-dash-grid">
    <div class="panel pm-chart"><div class="row"><h3 class="grow">Status Distribution</h3><span class="badge">Interactive</span></div><div id="pmDonut"></div><div class="pm-legend" id="pmLegend"></div></div>
    <div class="panel pm-chart"><div class="row"><h3 class="grow">Stream Health & Exception Concentration</h3><span class="badge">Click a stream</span></div><div id="pmStreams"></div></div>
  </div>
  <div class="panel pm-chart" style="margin-top:14px"><div class="row"><h3 class="grow">Monthly Delivery Trend</h3><span class="badge">Click a month</span></div><div id="pmMonthly"></div><div class="pm-legend" id="pmMonthlyLegend"></div></div>
</div>
<div class="pm-detail" id="pmDetail"><div class="pm-detail-box"><div class="pm-detail-head"><div><h2 id="pmDetailTitle" style="margin:0"></h2><div id="pmDetailSub" class="muted mini" style="margin-top:4px"></div></div><button class="btn" id="pmDetailClose">Close</button></div><div id="pmDetailBody" style="margin-top:14px"></div></div></div>
<script>
(function(){
 const colors={Completed:'#39d49a','On Track':'#5791ff','At Risk':'#ffc454',Delayed:'#ff6b80',Overdue:'#ff6b80'};
 const esc2=v=>String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const statusOf=t=>{const s=String(t.status||'');if(/complete|done|closed/i.test(s))return'Completed';if(/delay|overdue|late|blocked/i.test(s))return'Delayed';if(/risk/i.test(s))return'At Risk';return'On Track'};
 const getTasks=()=>{try{return (typeof project==='function'?(project().tasks||[]):[])}catch(e){return[]}};
 const open=(title,sub,tasks)=>{const modal=document.getElementById('pmDetail');document.getElementById('pmDetailTitle').textContent=title;document.getElementById('pmDetailSub').textContent=sub||'';const body=document.getElementById('pmDetailBody');if(!tasks.length){body.innerHTML='<div class="pm-empty">No matching task data.</div>'}else{body.innerHTML='<div class="tablewrap"><table><thead><tr><th>Task</th><th>Status</th><th>Stream</th><th>PIC</th><th>ETA</th><th>Priority</th><th>Dependency / Blocker</th><th>PMO Action</th></tr></thead><tbody>'+tasks.map(t=>'<tr><td><b>'+esc2(t.task)+'</b></td><td><span class="tag '+(/delay|overdue/i.test(t.status)?'red':/risk/i.test(t.status)?'amber':/complete/i.test(t.status)?'green':'blue')+'">'+esc2(statusOf(t))+'</span></td><td>'+esc2(t.stream)+'</td><td>'+esc2(t.pic)+'</td><td>'+esc2(t.eta)+'</td><td>'+esc2(t.priority)+'</td><td>'+esc2(t.dependency||'—')+'</td><td>'+esc2(t.action||'—')+'</td></tr>').join('')+'</tbody></table></div>'}modal.classList.add('open')};
 document.getElementById('pmDetailClose').onclick=()=>document.getElementById('pmDetail').classList.remove('open');document.getElementById('pmDetail').onclick=e=>{if(e.target.id==='pmDetail')e.currentTarget.classList.remove('open')};
 function renderStatus(){const ts=getTasks(),keys=['Completed','On Track','At Risk','Delayed'],counts=Object.fromEntries(keys.map(k=>[k,0]));ts.forEach(t=>counts[statusOf(t)]++);const total=ts.length||1;let start=-Math.PI/2,parts=keys.map(k=>{const a=counts[k]/total*Math.PI*2,b=start+a;const x1=50+42*Math.cos(start),y1=50+42*Math.sin(start),x2=50+42*Math.cos(b),y2=50+42*Math.sin(b),large=a>Math.PI?1:0;const d=counts[k]?`M50 50 L${x1} ${y1} A42 42 0 ${large} 1 ${x2} ${y2} Z`:'';start=b;return d?'<path d="'+d+'" fill="'+colors[k]+'" opacity=".95" data-status="'+k+'"></path>':''}).join('');document.getElementById('pmDonut').innerHTML='<div style="display:flex;align-items:center;justify-content:center;gap:18px"><svg viewBox="0 0 100 100" style="width:190px;height:190px;overflow:visible">'+parts+'<circle cx="50" cy="50" r="23" fill="#0d1a2b"></circle><text x="50" y="48" text-anchor="middle" fill="#eef5fc" font-size="9" font-weight="700">'+ts.length+'</text><text x="50" y="57" text-anchor="middle" fill="#91a4ba" font-size="4">TASKS</text></svg><div><div style="font-size:13px;color:#91a4ba">Portfolio status</div>'+keys.map(k=>'<div class="pm-click" data-status="'+k+'" style="margin-top:8px"><b style="color:'+colors[k]+'">'+counts[k]+'</b> '+k+' <span class="pm-kpi-note">'+Math.round(counts[k]/total*100)+'%</span></div>').join('')+'</div></div>';
 document.querySelectorAll('#pmDonut [data-status],#pmDonut .pm-click').forEach(el=>el.onclick=()=>{const k=el.dataset.status;open(k,'Status drill-down · '+counts[k]+' task(s)',ts.filter(t=>statusOf(t)===k))});document.getElementById('pmLegend').innerHTML=keys.map(k=>'<span class="pm-leg"><i class="pm-dot" style="background:'+colors[k]+'"></i>'+k+'</span>').join('')}
 function renderStreams(){const ts=getTasks(),m={};ts.forEach(t=>{const s=String(t.stream||'General');if(!m[s])m[s]={tasks:[],d:0,r:0,c:0,o:0};const x=m[s];x.tasks.push(t);const k=statusOf(t);if(k==='Delayed')x.d++;else if(k==='At Risk')x.r++;else if(k==='Completed')x.c++;else x.o++});const rows=Object.entries(m).map(([s,x])=>({s,...x,ex:x.d+x.r})).sort((a,b)=>b.ex-a.ex||b.tasks.length-a.tasks.length).slice(0,10);const max=Math.max(1,...rows.map(x=>x.ex));document.getElementById('pmStreams').innerHTML=rows.length?rows.map(x=>'<div class="pm-click" data-stream="'+esc2(x.s)+'" style="padding:8px 6px;border-bottom:1px solid #223a56"><div class="row"><b style="font-size:12px">'+esc2(x.s)+'</b><span class="mini muted">'+x.tasks.length+' tasks</span></div><div class="pm-bar-row"><span class="mini muted">Exceptions</span><div class="pm-bar"><i style="width:'+Math.max(2,x.ex/max*100)+'%;background:'+(x.d?'#ff6b80':'#ffc454')+'"></i></div><b>'+x.ex+'</b></div><div class="mini muted">🔴 '+x.d+' Delayed &nbsp; 🟠 '+x.r+' At Risk &nbsp; 🔵 '+x.o+' On Track &nbsp; 🟢 '+x.c+' Completed</div></div>').join(''):'<div class="pm-empty">No task data available.</div>';document.querySelectorAll('#pmStreams [data-stream]').forEach(el=>el.onclick=()=>{const s=el.dataset.stream;open(s,'Stream drill-down',ts.filter(t=>String(t.stream||'General')===s))})}
 function monthKey(t){const d=new Date(t.eta);if(isNaN(d))return'';return d.toLocaleString('en-US',{month:'short'})+' '+d.getFullYear()}
 function renderMonthly(){const ts=getTasks(),m={};ts.forEach(t=>{const k=monthKey(t);if(!k)return;if(!m[k])m[k]={tasks:[],Completed:0,'On Track':0,'At Risk':0,Delayed:0,date:new Date(t.eta)};m[k].tasks.push(t);m[k][statusOf(t)]++});const rows=Object.values(m).sort((a,b)=>a.date-b.date);if(!rows.length){document.getElementById('pmMonthly').innerHTML='<div class="pm-empty">No dated task data available for monthly trend.</div>';return}const max=Math.max(1,...rows.map(x=>x.tasks.length));document.getElementById('pmMonthly').innerHTML=rows.map(x=>{const seg=['Completed','On Track','At Risk','Delayed'].map(k=>x[k]?'<span style="display:block;height:'+Math.max(4,x[k]/x.tasks.length*100)+'%;background:'+colors[k]+'" title="'+k+': '+x[k]+'"></span>':'').join('');return '<div class="pm-click" data-month="'+esc2(monthKey({eta:x.date}))+'" style="display:inline-flex;vertical-align:bottom;flex-direction:column;align-items:center;width:'+Math.max(55,Math.min(110,86/rows.length*2))+'px;margin-right:8px"><div style="height:190px;width:42px;background:#12243a;border-radius:7px;display:flex;flex-direction:column;justify-content:flex-end;overflow:hidden"><div style="height:'+Math.max(5,x.tasks.length/max*100)+'%;display:flex;flex-direction:column-reverse">'+seg+'</div></div><b style="font-size:10px;margin-top:7px">'+x.date.toLocaleString('en-US',{month:'short'})+'</b><span class="mini muted">'+x.tasks.length+'</span></div>'}).join('');document.querySelectorAll('#pmMonthly [data-month]').forEach(el=>el.onclick=()=>{const k=el.dataset.month;open(k,'Monthly delivery drill-down',ts.filter(t=>monthKey(t)===k))});document.getElementById('pmMonthlyLegend').innerHTML=['Completed','On Track','At Risk','Delayed'].map(k=>'<span class="pm-leg"><i class="pm-dot" style="background:'+colors[k]+'"></i>'+k+'</span>').join('')}
 function init(){if(!document.getElementById('pmDash'))return;renderStatus();renderStreams();renderMonthly()}
 let tries=0;const timer=setInterval(()=>{tries++;try{if(typeof project==='function'&&document.getElementById('kpis')){init();clearInterval(timer)}}catch(e){}if(tries>60)clearInterval(timer)},250);
})();
</script>`}

export default {async fetch(request,env,ctx){
  const response=await base.fetch(request,env,ctx);
  const url=new URL(request.url);
  const ct=response.headers.get('content-type')||'';
  if(url.pathname==='/'&&ct.includes('text/html')){
    const text=await response.text();
    const injected=text.replace('</style></head>','</style>'+enhancement+'</head>').replace('<div class="hero"><h2>Project control, prioritised.</h2>','<div class="hero"><h2>Project control, prioritised.</h2>').replace('<div class="grid" id="kpis"></div>','<div class="grid" id="kpis"></div>'+injection());
    const headers=new Headers(response.headers);headers.set('content-type','text/html;charset=UTF-8');headers.set('cache-control','no-store');
    return new Response(injected,{status:response.status,headers});
  }
  return response;
}};
